/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedVerifyIdentityRouteImport } from './routes/_authenticated/verify-identity'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPassengerRouteImport } from './routes/_authenticated/passenger'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDriverRouteImport } from './routes/_authenticated/driver'
import { Route as AuthenticatedBecomeDriverRouteImport } from './routes/_authenticated/become-driver'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminVerificationsRouteImport } from './routes/_authenticated/admin.verifications'
import { Route as AuthenticatedPassengerRideRideIdRouteImport } from './routes/_authenticated/passenger.ride.$rideId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVerifyIdentityRoute =
  AuthenticatedVerifyIdentityRouteImport.update({
    id: '/verify-identity',
    path: '/verify-identity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPassengerRoute = AuthenticatedPassengerRouteImport.update({
  id: '/passenger',
  path: '/passenger',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriverRoute = AuthenticatedDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBecomeDriverRoute =
  AuthenticatedBecomeDriverRouteImport.update({
    id: '/become-driver',
    path: '/become-driver',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminVerificationsRoute =
  AuthenticatedAdminVerificationsRouteImport.update({
    id: '/verifications',
    path: '/verifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedPassengerRideRideIdRoute =
  AuthenticatedPassengerRideRideIdRouteImport.update({
    id: '/ride/$rideId',
    path: '/ride/$rideId',
    getParentRoute: () => AuthenticatedPassengerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/become-driver': typeof AuthenticatedBecomeDriverRoute
  '/driver': typeof AuthenticatedDriverRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/home': typeof AuthenticatedHomeRoute
  '/passenger': typeof AuthenticatedPassengerRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/verify-identity': typeof AuthenticatedVerifyIdentityRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/passenger/ride/$rideId': typeof AuthenticatedPassengerRideRideIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/become-driver': typeof AuthenticatedBecomeDriverRoute
  '/driver': typeof AuthenticatedDriverRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/home': typeof AuthenticatedHomeRoute
  '/passenger': typeof AuthenticatedPassengerRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/verify-identity': typeof AuthenticatedVerifyIdentityRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/passenger/ride/$rideId': typeof AuthenticatedPassengerRideRideIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/become-driver': typeof AuthenticatedBecomeDriverRoute
  '/_authenticated/driver': typeof AuthenticatedDriverRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/passenger': typeof AuthenticatedPassengerRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/verify-identity': typeof AuthenticatedVerifyIdentityRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/_authenticated/passenger/ride/$rideId': typeof AuthenticatedPassengerRideRideIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/become-driver'
    | '/driver'
    | '/history'
    | '/home'
    | '/passenger'
    | '/profile'
    | '/verify-identity'
    | '/wallet'
    | '/admin/verifications'
    | '/passenger/ride/$rideId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/become-driver'
    | '/driver'
    | '/history'
    | '/home'
    | '/passenger'
    | '/profile'
    | '/verify-identity'
    | '/wallet'
    | '/admin/verifications'
    | '/passenger/ride/$rideId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/become-driver'
    | '/_authenticated/driver'
    | '/_authenticated/history'
    | '/_authenticated/home'
    | '/_authenticated/passenger'
    | '/_authenticated/profile'
    | '/_authenticated/verify-identity'
    | '/_authenticated/wallet'
    | '/_authenticated/admin/verifications'
    | '/_authenticated/passenger/ride/$rideId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verify-identity': {
      id: '/_authenticated/verify-identity'
      path: '/verify-identity'
      fullPath: '/verify-identity'
      preLoaderRoute: typeof AuthenticatedVerifyIdentityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/passenger': {
      id: '/_authenticated/passenger'
      path: '/passenger'
      fullPath: '/passenger'
      preLoaderRoute: typeof AuthenticatedPassengerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/driver': {
      id: '/_authenticated/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof AuthenticatedDriverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/become-driver': {
      id: '/_authenticated/become-driver'
      path: '/become-driver'
      fullPath: '/become-driver'
      preLoaderRoute: typeof AuthenticatedBecomeDriverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/verifications': {
      id: '/_authenticated/admin/verifications'
      path: '/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AuthenticatedAdminVerificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/passenger/ride/$rideId': {
      id: '/_authenticated/passenger/ride/$rideId'
      path: '/ride/$rideId'
      fullPath: '/passenger/ride/$rideId'
      preLoaderRoute: typeof AuthenticatedPassengerRideRideIdRouteImport
      parentRoute: typeof AuthenticatedPassengerRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminVerificationsRoute: typeof AuthenticatedAdminVerificationsRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminVerificationsRoute: AuthenticatedAdminVerificationsRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedPassengerRouteChildren {
  AuthenticatedPassengerRideRideIdRoute: typeof AuthenticatedPassengerRideRideIdRoute
}

const AuthenticatedPassengerRouteChildren: AuthenticatedPassengerRouteChildren =
  {
    AuthenticatedPassengerRideRideIdRoute:
      AuthenticatedPassengerRideRideIdRoute,
  }

const AuthenticatedPassengerRouteWithChildren =
  AuthenticatedPassengerRoute._addFileChildren(
    AuthenticatedPassengerRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBecomeDriverRoute: typeof AuthenticatedBecomeDriverRoute
  AuthenticatedDriverRoute: typeof AuthenticatedDriverRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedPassengerRoute: typeof AuthenticatedPassengerRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedVerifyIdentityRoute: typeof AuthenticatedVerifyIdentityRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBecomeDriverRoute: AuthenticatedBecomeDriverRoute,
  AuthenticatedDriverRoute: AuthenticatedDriverRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedPassengerRoute: AuthenticatedPassengerRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedVerifyIdentityRoute: AuthenticatedVerifyIdentityRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
