/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedVerifyIdentityRouteImport } from './routes/_authenticated/verify-identity'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPassengerRouteImport } from './routes/_authenticated/passenger'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDriverRouteImport } from './routes/_authenticated/driver'
import { Route as AuthenticatedBecomeDriverRouteImport } from './routes/_authenticated/become-driver'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedSettingsTermsRouteImport } from './routes/_authenticated/settings.terms'
import { Route as AuthenticatedSettingsSupportRouteImport } from './routes/_authenticated/settings.support'
import { Route as AuthenticatedSettingsPrivacyRouteImport } from './routes/_authenticated/settings.privacy'
import { Route as AuthenticatedSettingsAddressesRouteImport } from './routes/_authenticated/settings.addresses'
import { Route as AuthenticatedSettingsAboutRouteImport } from './routes/_authenticated/settings.about'
import { Route as AuthenticatedAdminVerificationsRouteImport } from './routes/_authenticated/admin.verifications'
import { Route as AuthenticatedPassengerRideRideIdRouteImport } from './routes/_authenticated/passenger.ride.$rideId'
import { Route as AuthenticatedPassengerRideRideIdWaitingRouteImport } from './routes/_authenticated/passenger.ride.$rideId.waiting'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVerifyIdentityRoute =
  AuthenticatedVerifyIdentityRouteImport.update({
    id: '/verify-identity',
    path: '/verify-identity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPassengerRoute = AuthenticatedPassengerRouteImport.update({
  id: '/passenger',
  path: '/passenger',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriverRoute = AuthenticatedDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBecomeDriverRoute =
  AuthenticatedBecomeDriverRouteImport.update({
    id: '/become-driver',
    path: '/become-driver',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsTermsRoute =
  AuthenticatedSettingsTermsRouteImport.update({
    id: '/terms',
    path: '/terms',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsSupportRoute =
  AuthenticatedSettingsSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsPrivacyRoute =
  AuthenticatedSettingsPrivacyRouteImport.update({
    id: '/privacy',
    path: '/privacy',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAddressesRoute =
  AuthenticatedSettingsAddressesRouteImport.update({
    id: '/addresses',
    path: '/addresses',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedSettingsAboutRoute =
  AuthenticatedSettingsAboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => AuthenticatedSettingsRoute,
  } as any)
const AuthenticatedAdminVerificationsRoute =
  AuthenticatedAdminVerificationsRouteImport.update({
    id: '/verifications',
    path: '/verifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedPassengerRideRideIdRoute =
  AuthenticatedPassengerRideRideIdRouteImport.update({
    id: '/ride/$rideId',
    path: '/ride/$rideId',
    getParentRoute: () => AuthenticatedPassengerRoute,
  } as any)
const AuthenticatedPassengerRideRideIdWaitingRoute =
  AuthenticatedPassengerRideRideIdWaitingRouteImport.update({
    id: '/waiting',
    path: '/waiting',
    getParentRoute: () => AuthenticatedPassengerRideRideIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/become-driver': typeof AuthenticatedBecomeDriverRoute
  '/driver': typeof AuthenticatedDriverRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/home': typeof AuthenticatedHomeRoute
  '/passenger': typeof AuthenticatedPassengerRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/verify-identity': typeof AuthenticatedVerifyIdentityRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/settings/about': typeof AuthenticatedSettingsAboutRoute
  '/settings/addresses': typeof AuthenticatedSettingsAddressesRoute
  '/settings/privacy': typeof AuthenticatedSettingsPrivacyRoute
  '/settings/support': typeof AuthenticatedSettingsSupportRoute
  '/settings/terms': typeof AuthenticatedSettingsTermsRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/passenger/ride/$rideId': typeof AuthenticatedPassengerRideRideIdRouteWithChildren
  '/passenger/ride/$rideId/waiting': typeof AuthenticatedPassengerRideRideIdWaitingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/become-driver': typeof AuthenticatedBecomeDriverRoute
  '/driver': typeof AuthenticatedDriverRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/home': typeof AuthenticatedHomeRoute
  '/passenger': typeof AuthenticatedPassengerRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/verify-identity': typeof AuthenticatedVerifyIdentityRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/settings/about': typeof AuthenticatedSettingsAboutRoute
  '/settings/addresses': typeof AuthenticatedSettingsAddressesRoute
  '/settings/privacy': typeof AuthenticatedSettingsPrivacyRoute
  '/settings/support': typeof AuthenticatedSettingsSupportRoute
  '/settings/terms': typeof AuthenticatedSettingsTermsRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/passenger/ride/$rideId': typeof AuthenticatedPassengerRideRideIdRouteWithChildren
  '/passenger/ride/$rideId/waiting': typeof AuthenticatedPassengerRideRideIdWaitingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/become-driver': typeof AuthenticatedBecomeDriverRoute
  '/_authenticated/driver': typeof AuthenticatedDriverRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/passenger': typeof AuthenticatedPassengerRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteWithChildren
  '/_authenticated/verify-identity': typeof AuthenticatedVerifyIdentityRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/admin/verifications': typeof AuthenticatedAdminVerificationsRoute
  '/_authenticated/settings/about': typeof AuthenticatedSettingsAboutRoute
  '/_authenticated/settings/addresses': typeof AuthenticatedSettingsAddressesRoute
  '/_authenticated/settings/privacy': typeof AuthenticatedSettingsPrivacyRoute
  '/_authenticated/settings/support': typeof AuthenticatedSettingsSupportRoute
  '/_authenticated/settings/terms': typeof AuthenticatedSettingsTermsRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/passenger/ride/$rideId': typeof AuthenticatedPassengerRideRideIdRouteWithChildren
  '/_authenticated/passenger/ride/$rideId/waiting': typeof AuthenticatedPassengerRideRideIdWaitingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/become-driver'
    | '/driver'
    | '/history'
    | '/home'
    | '/passenger'
    | '/profile'
    | '/settings'
    | '/verify-identity'
    | '/wallet'
    | '/admin/verifications'
    | '/settings/about'
    | '/settings/addresses'
    | '/settings/privacy'
    | '/settings/support'
    | '/settings/terms'
    | '/settings/'
    | '/passenger/ride/$rideId'
    | '/passenger/ride/$rideId/waiting'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/become-driver'
    | '/driver'
    | '/history'
    | '/home'
    | '/passenger'
    | '/profile'
    | '/verify-identity'
    | '/wallet'
    | '/admin/verifications'
    | '/settings/about'
    | '/settings/addresses'
    | '/settings/privacy'
    | '/settings/support'
    | '/settings/terms'
    | '/settings'
    | '/passenger/ride/$rideId'
    | '/passenger/ride/$rideId/waiting'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/become-driver'
    | '/_authenticated/driver'
    | '/_authenticated/history'
    | '/_authenticated/home'
    | '/_authenticated/passenger'
    | '/_authenticated/profile'
    | '/_authenticated/settings'
    | '/_authenticated/verify-identity'
    | '/_authenticated/wallet'
    | '/_authenticated/admin/verifications'
    | '/_authenticated/settings/about'
    | '/_authenticated/settings/addresses'
    | '/_authenticated/settings/privacy'
    | '/_authenticated/settings/support'
    | '/_authenticated/settings/terms'
    | '/_authenticated/settings/'
    | '/_authenticated/passenger/ride/$rideId'
    | '/_authenticated/passenger/ride/$rideId/waiting'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verify-identity': {
      id: '/_authenticated/verify-identity'
      path: '/verify-identity'
      fullPath: '/verify-identity'
      preLoaderRoute: typeof AuthenticatedVerifyIdentityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/passenger': {
      id: '/_authenticated/passenger'
      path: '/passenger'
      fullPath: '/passenger'
      preLoaderRoute: typeof AuthenticatedPassengerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/driver': {
      id: '/_authenticated/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof AuthenticatedDriverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/become-driver': {
      id: '/_authenticated/become-driver'
      path: '/become-driver'
      fullPath: '/become-driver'
      preLoaderRoute: typeof AuthenticatedBecomeDriverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/terms': {
      id: '/_authenticated/settings/terms'
      path: '/terms'
      fullPath: '/settings/terms'
      preLoaderRoute: typeof AuthenticatedSettingsTermsRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/support': {
      id: '/_authenticated/settings/support'
      path: '/support'
      fullPath: '/settings/support'
      preLoaderRoute: typeof AuthenticatedSettingsSupportRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/privacy': {
      id: '/_authenticated/settings/privacy'
      path: '/privacy'
      fullPath: '/settings/privacy'
      preLoaderRoute: typeof AuthenticatedSettingsPrivacyRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/addresses': {
      id: '/_authenticated/settings/addresses'
      path: '/addresses'
      fullPath: '/settings/addresses'
      preLoaderRoute: typeof AuthenticatedSettingsAddressesRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/settings/about': {
      id: '/_authenticated/settings/about'
      path: '/about'
      fullPath: '/settings/about'
      preLoaderRoute: typeof AuthenticatedSettingsAboutRouteImport
      parentRoute: typeof AuthenticatedSettingsRoute
    }
    '/_authenticated/admin/verifications': {
      id: '/_authenticated/admin/verifications'
      path: '/verifications'
      fullPath: '/admin/verifications'
      preLoaderRoute: typeof AuthenticatedAdminVerificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/passenger/ride/$rideId': {
      id: '/_authenticated/passenger/ride/$rideId'
      path: '/ride/$rideId'
      fullPath: '/passenger/ride/$rideId'
      preLoaderRoute: typeof AuthenticatedPassengerRideRideIdRouteImport
      parentRoute: typeof AuthenticatedPassengerRoute
    }
    '/_authenticated/passenger/ride/$rideId/waiting': {
      id: '/_authenticated/passenger/ride/$rideId/waiting'
      path: '/waiting'
      fullPath: '/passenger/ride/$rideId/waiting'
      preLoaderRoute: typeof AuthenticatedPassengerRideRideIdWaitingRouteImport
      parentRoute: typeof AuthenticatedPassengerRideRideIdRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminVerificationsRoute: typeof AuthenticatedAdminVerificationsRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminVerificationsRoute: AuthenticatedAdminVerificationsRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedPassengerRideRideIdRouteChildren {
  AuthenticatedPassengerRideRideIdWaitingRoute: typeof AuthenticatedPassengerRideRideIdWaitingRoute
}

const AuthenticatedPassengerRideRideIdRouteChildren: AuthenticatedPassengerRideRideIdRouteChildren =
  {
    AuthenticatedPassengerRideRideIdWaitingRoute:
      AuthenticatedPassengerRideRideIdWaitingRoute,
  }

const AuthenticatedPassengerRideRideIdRouteWithChildren =
  AuthenticatedPassengerRideRideIdRoute._addFileChildren(
    AuthenticatedPassengerRideRideIdRouteChildren,
  )

interface AuthenticatedPassengerRouteChildren {
  AuthenticatedPassengerRideRideIdRoute: typeof AuthenticatedPassengerRideRideIdRouteWithChildren
}

const AuthenticatedPassengerRouteChildren: AuthenticatedPassengerRouteChildren =
  {
    AuthenticatedPassengerRideRideIdRoute:
      AuthenticatedPassengerRideRideIdRouteWithChildren,
  }

const AuthenticatedPassengerRouteWithChildren =
  AuthenticatedPassengerRoute._addFileChildren(
    AuthenticatedPassengerRouteChildren,
  )

interface AuthenticatedSettingsRouteChildren {
  AuthenticatedSettingsAboutRoute: typeof AuthenticatedSettingsAboutRoute
  AuthenticatedSettingsAddressesRoute: typeof AuthenticatedSettingsAddressesRoute
  AuthenticatedSettingsPrivacyRoute: typeof AuthenticatedSettingsPrivacyRoute
  AuthenticatedSettingsSupportRoute: typeof AuthenticatedSettingsSupportRoute
  AuthenticatedSettingsTermsRoute: typeof AuthenticatedSettingsTermsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteChildren: AuthenticatedSettingsRouteChildren = {
  AuthenticatedSettingsAboutRoute: AuthenticatedSettingsAboutRoute,
  AuthenticatedSettingsAddressesRoute: AuthenticatedSettingsAddressesRoute,
  AuthenticatedSettingsPrivacyRoute: AuthenticatedSettingsPrivacyRoute,
  AuthenticatedSettingsSupportRoute: AuthenticatedSettingsSupportRoute,
  AuthenticatedSettingsTermsRoute: AuthenticatedSettingsTermsRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
}

const AuthenticatedSettingsRouteWithChildren =
  AuthenticatedSettingsRoute._addFileChildren(
    AuthenticatedSettingsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBecomeDriverRoute: typeof AuthenticatedBecomeDriverRoute
  AuthenticatedDriverRoute: typeof AuthenticatedDriverRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedPassengerRoute: typeof AuthenticatedPassengerRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRouteWithChildren
  AuthenticatedVerifyIdentityRoute: typeof AuthenticatedVerifyIdentityRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBecomeDriverRoute: AuthenticatedBecomeDriverRoute,
  AuthenticatedDriverRoute: AuthenticatedDriverRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedPassengerRoute: AuthenticatedPassengerRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRouteWithChildren,
  AuthenticatedVerifyIdentityRoute: AuthenticatedVerifyIdentityRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
